kwejk_mems_homepage:
    path:     /hello/{name}
    defaults: { _controller: KwejkMemsBundle:Default:index }

kwejk_mems_add:
    path: /panel/add
    defaults: {_controller: KwejkMemsBundle:Mems:add}

kwejk_mems_list:
    path:     /
    defaults: { _controller: KwejkMemsBundle:Mems:list }

kwejk_mems_show:
    path:     /{slug}
    defaults: { _controller: KwejkMemsBundle:Mems:show }

kwejk_mems_comment_new:
    path:     /comment/new
    defaults: { _controller: KwejkMemsBundle:Comment:new }

kwejk_mems_comment_edit:
    path:     /comment/edit/{id}
    defaults: { _controller: KwejkMemsBundle:Comment:edit }

add_rating:
    path:     /addRating
    defaults: { _controller: KwejkMemsBundle:Rating:addRating }

kwejk_mems_poczekalnia:
    path:   /poczekalnia
    defaults: { _controller: KwejkBundle:Mems:poczekalnia }