fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

KwejkUserBundle_admin_kwejk_user_bundle_user:
    resource: "@KwejkUserBundle/Controller/User/"
    type:     admingenerator
    prefix:   /admin/user

KwejkAdminBundle_admin_kwejk_admin_bundle_mem:
    resource: "@KwejkAdminBundle/Controller/Mem/"
    type:     admingenerator
    prefix:   /admin/mem

kwejk_core:
    resource: "@KwejkCoreBundle/Resources/config/routing.yml"
    prefix:   /


#
#kwejk_layout:
#    resource: "@KwejkLayoutBundle/Resources/config/routing.yml"
#    prefix:   /

kwejk_mems:
    resource: "@KwejkMemsBundle/Resources/config/routing.yml"
    prefix:   /

kwejk_user:
    resource: "@KwejkUserBundle/Resources/config/routing.yml"
    prefix:   /

kwejk_admin:
    resource: "@KwejkAdminBundle/Resources/config/routing.yml"
    prefix:   /

